export const GET_FORCAST_DATA = {
  pending: "GET_FORCAST_DATA_PENDING",
  fulfilled: "GET_FORCAST_DATA_FULFILLED",
  rejected: "GET_FORCAST_DATA_REJECTED",
  reset: "GET_FORCAST_DATA_RESET",
};

export const RESET_STATE = 'RESET_STATE'